## Rubric



Scoring: Out of 10 points

- Each Developing  => -2 pts
- Each Unsatisfactory/Missing => -4 pts
  - until the score is 

If students address the detailed feedback in a future checkpoint they will earn these points back


|                  | Unsatisfactory                                                                                                                                                                                                    | Developing                                                                                                                                                                                              | Proficient                                     | Excellent                                                                                                                              |
|------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------|----------------------------------------------------------------------------------------------------------------------------------------|
| Data relevance   | Did not have data relevant to their question. Or the datasets don't work together because there is no way to line them up against each other. If there are multiple datasets, most of them have this trouble | Data was only tangentially relevant to the question or a bad proxy for the question. If there are multiple datasets, some of them may be irrelevant or can't be easily combined.                       | All data sources are relevant to the question. | Multiple data sources for each aspect of the project. It's clear how the data supports the needs of the project.                         |
| Data description | Dataset or its cleaning procedures are not described. If there are multiple datasets, most have this trouble                                                                                              | Data was not fully described. If there are multiple datasets, some of them are not fully described                                                                                                      | Data was fully described                       | The details of the data descriptions and perhaps some very basic EDA also make it clear how the data supports the needs of the project. |
| Data wrangling   | Did not obtain data. They did not clean/tidy the data they obtained.  If there are multiple datasets, most have this trouble                                                                                 | Data was partially cleaned or tidied. Perhaps you struggled to verify that the data was clean because they did not present it well. If there are multiple datasets, some have this trouble | The data is cleaned and tidied.                | The data is spotless and they used tools to visualize the data cleanliness and you were convinced at first glance                      |

# COGS 108 - Data Checkpoint

## Authors

Instructions: REPLACE the contents of this cell with your team list and their contributions. Note that this will change over the course of the checkpoints

This is a modified [CRediT taxonomy of contributions](https://credit.niso.org). For each group member please list how they contributed to this project using these terms:
> Analysis, Background research, Conceptualization, Data curation, Experimental investigation, Methodology, Project administration, Software, Visualization, Writing – original draft, Writing – review & editing

- Alice Anderson: Conceptualization, Data curation, Methodology, Writing - original draft
- Bob Barker:  Analysis, Software, Visualization
- Charlie Chang: Project administration, Software, Writing - review & editing
- Dani Delgado: Analysis, Background research, Visualization, Writing - original draft

## Research Question

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Background and Prior Work

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Hypothesis

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Data

### Data overview

Instructions: REPLACE the contents of this cell with descriptions of your actual datasets.

For each dataset include the following information
#### Dataset #1: 
  - Dataset Name: Data Center facilities in the US
  - Link to the dataset: https://data.msdlive.org/records/p147s-4h760
  - Number of observations: 1479
  - Number of variables: 13
  - Description of the variables most relevant to this project: state, county, operator, sqft
  - Descriptions of any shortcomings this dataset has with respect to the project: doesn't give the city
#### Dataset #2 
  - Dataset Name: County GDP summary- percent change from preceding period (2022-2024)
  - Link to the dataset: https://apps.bea.gov/itable/?ReqID=70&step=1&_gl=1*1fpvxvi*_ga*MTgyMzE3ODI5My4xNzcxNDYxNzcw*_ga_J4698JNNFT*czE3NzE0NjE3NjkkbzEkZzEkdDE3NzE0NjM2NDQkajM5JGwwJGgw#eyJhcHBpZCI6NzAsInN0ZXBzIjpbMSwyOSwyNSwzMSwyNiwyNywzMF0sImRhdGEiOltbIlRhYmxlSWQiLCI1MzMiXSxbIk1ham9yX0FyZWEiLCI0Il0sWyJTdGF0ZSIsWyJYWCJdXSxbIkFyZWEiLFsiWFgiXV0sWyJTdGF0aXN0aWMiLFsiMSJdXSxbIlVuaXRfb2ZfbWVhc3VyZSIsIlBlcmNlbnRDaGFuZ2UiXSxbIlllYXIiLFsiMjAyNCIsIjIwMjMiLCIyMDIyIl1dLFsiWWVhckJlZ2luIiwiLTEiXSxbIlllYXJfRW5kIiwiLTEiXV19
  - Number of observations: 3138
  - Number of variables: 5
  - Description of the variables most relevant to this project
  - Descriptions of any shortcomings this dataset has with respect to the project
#### Dataset #3 
  - Dataset Name: 
  - Link to the dataset: 
  - Number of observations: 
  - Number of variables: 
  - Description of the variables most relevant to this project
  - Descriptions of any shortcomings this dataset has with respect to the project
#### Dataset #4 
  - Dataset Name: 
  - Link to the dataset: 
  - Number of observations: 
  - Number of variables: 
  - Description of the variables most relevant to this project
  - Descriptions of any shortcomings this dataset has with respect to the project
#### Dataset #5 
  - Dataset Name: 
  - Link to the dataset: 
  - Number of observations: 
  - Number of variables: 
  - Description of the variables most relevant to this project
  - Descriptions of any shortcomings this dataset has with respect to the project

Each dataset deserves either a set of bullet points as above or a few sentences if you prefer that method.

If you plan to use multiple datasets, add a few sentences about how you plan to combine these datasets.

In [1]:
# Run this code every time when you're actively developing modules in .py files.  It's not needed if you aren't making modules
#
## this code is necessary for making sure that any modules we load are updated here 
## when their source code .py files are modified

%load_ext autoreload
%autoreload 2

In [23]:
# Setup code -- this only needs to be run once after cloning the repo!
# this code downloads the data from its source to the `data/00-raw/` directory
# if the data hasn't updated you don't need to do this again!

# if you don't already have these packages (you should!) uncomment this line
# %pip install requests tqdm

import sys
sys.path.append('./modules') # this tells python where to look for modules to import

import get_data # this is where we get the function we need to download data

# replace the urls and filenames in this list with your actual datafiles
# yes you can use Google drive share links or whatever
# format is a list of dictionaries; 
# each dict has keys of 
#   'url' where the resource is located
#   'filename' for the local filename where it will be stored 
datafiles = [
    { 'url': 'https://drive.google.com/uc?export=download&id=1QIQEXyJFnfvVRdXEb4X4XXXIPql21dlD', 'filename':'datacenters.csv'},
    { 'url': 'https://drive.google.com/uc?export=download&id=1rJnAzG1hrLeIhdGgAQmpKnX_Jsw6qCxv', 'filename':'countygdp.csv'}
]

get_data.get_raw(datafiles,destination_directory='data/00-raw/')

Overall Download Progress:   0%|          | 0/2 [00:00<?, ?it/s]
Downloading datacenters.csv:   0%|          | 0.00/189k [00:00<?, ?B/s]
Overall Download Progress:  50%|█████     | 1/2 [00:01<00:01,  1.34s/it][A

Successfully downloaded: datacenters.csv

Downloading countygdp.csv:   0%|          | 0.00/111k [00:00<?, ?B/s]
Overall Download Progress: 100%|██████████| 2/2 [00:03<00:00,  1.63s/it]

Successfully downloaded: countygdp.csv

### Dataset #1- Data Center facilities in the US

Instructions: 
1. Change the header from Dataset #1 to something more descriptive of the dataset
2. Write a few paragraphs about this dataset. Make sure to cover
   1. Describe the important metrics, what units they are in, and giv some sense of what they mean.  For example "Fasting blood glucose in units of mg glucose per deciliter of blood.  Normal values for healthy individuals range from 70 to 100 mg/dL.  Values 100-125 are prediabetic and values >125mg/dL indicate diabetes. Values <70 indicate hypoglycemia. Fasting idicates the patient hasn't eaten in the last 8 hours.  If blood glucose is >250 or <50 at any time (regardless of the time of last meal) the patient's life may be in immediate danger"
   2. If there are any major concerns with the dataset, describe them. For example "Dataset is composed of people who are serious enough about eating healthy that they voluntarily downloaded an app dedicated to tracking their eating patterns. This sample is likely biased because of that self-selection. These people own smartphones and may be healthier and may have more disposable income than the average person.  Those who voluntarily log conscientiously and for long amounts of time are also likely even more interested in health than those who download the app and only log a bit before getting tired of it"
3. Use the cell below to 
    1. load the dataset 
    2. make the dataset tidy or demonstrate that it was already tidy
    3. demonstrate the size of the dataset
    4. find out how much data is missing, where its missing, and if its missing at random or seems to have any systematic relationships in its missingness
    5. find and flag any outliers or suspicious entries
    6. clean the data or demonstrate that it was already clean.  You may choose how to deal with missingness (dropna of fillna... how='any' or 'all') and you should justify your choice in some way
    7. You will load raw data from `data/00-raw/`, you will (optionally) write intermediate stages of your work to `data/01-interim` and you will write the final fully wrangled version of your data to `data/02-processed`
4. Optionally you can also show some summary statistics for variables that you think are important to the project
5. Feel free to add more cells here if that's helpful for you

In [2]:
import pandas as pd

In [3]:
## A. this is a preview of the dataset
df_datacenters = pd.read_csv('data/00-raw/datacenters.csv')
df_datacenters.head()

,id,state,state_abb,state_id,county,county_id,operator,ref,name,sqft,lon,lat,type
0,2744301,New Jersey,NJ,34,Middlesex County,23,NaN,NaN,Verizon,105786.0,-74.496521,40.544256,building
1,9474864,North Carolina,NC,37,Caldwell County,27,Google,NaN,Google Data Center,3407194.0,-81.546515,35.894738,campus
2,13924557,Iowa,IA,19,Polk County,153,Microsoft,NaN,Project Alluvion,11169421.0,-93.711830,41.515967,campus
3,14593270,North Carolina,NC,37,Catawba County,35,NaN,NaN,Apple - Maiden Data Center,5431080.0,-81.261809,35.588771,campus
4,14930068,New Mexico,NM,35,Bernalillo County,1,Sandia National Laboratories,880,HPC,158463.0,-106.542822,35.049942,building

In [ ]:
## B. tidy dataset

In [11]:
## C. this is the size of the dataset
df_datacenters.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1479 entries, 0 to 1478
Data columns (total 13 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   id         1479 non-null   int64
 1   state      1479 non-null   object
 2   state_abb  1479 non-null   object
 3   state_id   1479 non-null   int64
 4   county     1479 non-null   object
 5   county_id  1479 non-null   int64
 6   operator   960 non-null    object
 7   ref        374 non-null    object
 8   name       1204 non-null   object
 9   sqft       1374 non-null   float64
 10  lon        1479 non-null   float64
 11  lat        1479 non-null   float64
 12  type       1479 non-null   object
dtypes: float64(3), int64(3), object(7)
memory usage: 150.3+ KB

#### Dataset #1 D. missing data
As we can see above, the columns that contain missing data are operate, ref, name and sqft.

#### Dataset #1 F.clean data
To clean the data, I will drop irrelevant columns, and show the datatypes are correct for the desired calculations. I will also remove the word County from the entries in county.

In [79]:
## Dataset #1 F.clean data
df_datacenters = df_datacenters.drop(columns=['state_abb',
                                              'state_id',
                                              'county_id',
                                              'ref',
                                              'lon',
                                              'lat',
                                              'type'])

In [83]:
## Dataset #1 F.clean data- renaming entries in county
df_datacenters['county'] = df_datacenters['county'].str.replace('County', '', regex=False)
df_datacenters

,id,state,county,operator,name,sqft
0,2744301,New Jersey,Middlesex,NaN,Verizon,105786.0
1,9474864,North Carolina,Caldwell,Google,Google Data Center,3407194.0
2,13924557,Iowa,Polk,Microsoft,Project Alluvion,11169421.0
3,14593270,North Carolina,Catawba,NaN,Apple - Maiden Data Center,5431080.0
4,14930068,New Mexico,Bernalillo,Sandia National Laboratories,HPC,158463.0
...,...,...,...,...,...,...
1474,13226718075,Wisconsin,Dane,Lumen Technologies,Lumen Madison 1 Data Center,NaN
1475,13311012216,Nevada,Clark,Fiberhub,Fiberhub LAS1,NaN
1476,13409186015,Pennsylvania,Montgomery,NaN,DāStor: 3400 Horizon Drive,NaN
1477,13465438761,Texas,Dallas,NaN,Rad Web Hosting,NaN
1478,13527396782,Washington,Snohomish,NaN,NaN,NaN

#### Dataset #1 summary statistics

In [84]:
## which counties have the most data centers?
df_datacenters.groupby('county').size().sort_values(ascending=False)

county
Loudoun            213
Santa Clara         75
Maricopa            63
Prince William      63
Grant               39
                  ...
Muskogee             1
Fairfield            1
Floyd                1
Morgan               1
Wood                 1
Length: 221, dtype: int64

In [85]:
## which states have the most data centers?
df_datacenters.groupby('state').size().sort_values(ascending=False).head()

state
Virginia      319
Texas         127
California    112
Oregon        109
Ohio           93
dtype: int64

### Dataset #2: County GDP summary- percent change from preceding period (2022-2024)

1. Change the header from Dataset #1 to something more descriptive of the dataset
2. Write a few paragraphs about this dataset. Make sure to cover
   1. Describe the important metrics, what units they are in, and giv some sense of what they mean.  For example "Fasting blood glucose in units of mg glucose per deciliter of blood.  Normal values for healthy individuals range from 70 to 100 mg/dL.  Values 100-125 are prediabetic and values >125mg/dL indicate diabetes. Values <70 indicate hypoglycemia. Fasting idicates the patient hasn't eaten in the last 8 hours.  If blood glucose is >250 or <50 at any time (regardless of the time of last meal) the patient's life may be in immediate danger"
   2. If there are any major concerns with the dataset, describe them. For example "Dataset is composed of people who are serious enough about eating healthy that they voluntarily downloaded an app dedicated to tracking their eating patterns. This sample is likely biased because of that self-selection. These people own smartphones and may be healthier and may have more disposable income than the average person.  Those who voluntarily log conscientiously and for long amounts of time are also likely even more interested in health than those who download the app and only log a bit before getting tired of it"
3. Use the cell below to 
    1. load the dataset 
    2. make the dataset tidy or demonstrate that it was already tidy
    3. demonstrate the size of the dataset
    4. find out how much data is missing, where its missing, and if its missing at random or seems to have any systematic relationships in its missingness
    5. find and flag any outliers or suspicious entries
    6. clean the data or demonstrate that it was already clean.  You may choose how to deal with missingness (dropna of fillna... how='any' or 'all') and you should justify your choice in some way
    7. You will load raw data from `data/00-raw/`, you will (optionally) write intermediate stages of your work to `data/01-interim` and you will write the final fully wrangled version of your data to `data/02-processed`
4. Optionally you can also show some summary statistics for variables that you think are important to the project
5. Feel free to add more cells here if that's helpful for you

In [98]:
## A. preview of the dataset
df_countygdp = pd.read_csv('data/00-raw/countygdp.csv', skiprows=3)
df_countygdp

,GeoFIPS,GeoName,2022,2023,2024
0,01001,"Autauga, AL",8.4,1.3,-7.8
1,01003,"Baldwin, AL",6.1,7.6,2.8
2,01005,"Barbour, AL",-1.2,-2.4,2.4
3,01007,"Bibb, AL",-0.4,2.8,0.9
4,01009,"Blount, AL",0.8,4.3,8.2
...,...,...,...,...,...
3133,"* Shannon County, SD was renamed to Oglala Lak...",NaN,NaN,NaN,NaN
3134,* Virginia combination areas consist of one or...,NaN,NaN,NaN,NaN
3135,* Estimates for 2024 forward reflect Connectic...,NaN,NaN,NaN,NaN
3136,(NA) Not available.,NaN,NaN,NaN,NaN
3137,"Last updated: February 5, 2026-- new statist...",NaN,NaN,NaN,NaN

In [99]:
## B. tidying dataset
df_countygdp.isnull().sum()

GeoFIPS     0
GeoName    11
2022       11
2023       11
2024       11
dtype: int64

In [100]:
## B. tidying dataset
df_countygdp.tail(11)

                                                GeoFIPS GeoName 2022 2023 2024
3127                                   Legend/Footnotes     NaN  NaN  NaN  NaN
3128  * Estimates from 2008 forward separate Skagway...     NaN  NaN  NaN  NaN
3129  * Wade Hampton Census Area was renamed Kusilva...     NaN  NaN  NaN  NaN
3130  * On January 2, 2019, two new county equivalen...     NaN  NaN  NaN  NaN
3131  * Broomfield County, CO, was created from part...     NaN  NaN  NaN  NaN
3132  * Kalawao County, Hawaii is combined with Maui...     NaN  NaN  NaN  NaN
3133  * Shannon County, SD was renamed to Oglala Lak...     NaN  NaN  NaN  NaN
3134  * Virginia combination areas consist of one or...     NaN  NaN  NaN  NaN
3135  * Estimates for 2024 forward reflect Connectic...     NaN  NaN  NaN  NaN
3136                                (NA) Not available.     NaN  NaN  NaN  NaN
3137    Last updated: February 5, 2026-- new statist...     NaN  NaN  NaN  NaN

#### Dataset #2 B. tidying dataset
We can see from the code above that the bottom 11 rows contain null values because it was intended to be a legend/footnote. The legend/footnote contains information about county name changes which are not relevant to our research question. I will now drop these rows.

In [101]:
df_countygdp = df_countygdp.iloc[:-11]

In [102]:
## C. dataset size
df_countygdp.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3127 entries, 0 to 3126
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   GeoFIPS  3127 non-null   object
 1   GeoName  3127 non-null   object
 2   2022     3127 non-null   object
 3   2023     3127 non-null   object
 4   2024     3127 non-null   object
dtypes: object(5)
memory usage: 122.3+ KB

In [103]:
## D. no more missing data
df_countygdp.isnull().sum()

GeoFIPS    0
GeoName    0
2022       0
2023       0
2024       0
dtype: int64

In [104]:
## E. outliers

# finding outliers for 2022
#Q1 = df_countygdp['2022'].quantile(0.25)
#Q3 = df_countygdp['2022'].quantile(0.75)
#IQR = Q3 - Q1
#outliers_2022 = df_countygdp[(df_countygdp['2022'] < Q1 - 1.5*IQR) | (df_countygdp['2022'] > Q3 + 1.5*IQR)]
#print(outliers_2022)

#### Dataset #2 E. outliers
I have found the statistical outliers from 2022. However, based on the nature of this dataset, the outliers are not suspicious values. There is natural variability in the gdp of different counties, whether from large companies ceasing operations in the area to natural disaster effects. Thus, it does not make sense at this time to drop these outliers or calculate the outliers for the other years.

#### Dataset #2 F. cleaning data
As mentioned above (tidying data), I have removed the missing values from the dataset. As you can see below, the data types are correct (numeric), allowing for calculations. To further clean the dataset, I will drop the GeoFIPS column because it's irrelevant and rename and reformat the datapoints in GeoNames (eg. Autauga, AL -> Autauga). I will change the format to match dataset #1 if we decide to merge these dfs in the future.

In [105]:
## Dataset #2 F. cleaning data
print(df_countygdp.dtypes)

GeoFIPS    object
GeoName    object
2022       object
2023       object
2024       object
dtype: object

In [106]:
## Dataset #2 F. cleaning data
#dropping geofips
df_countygdp = df_countygdp.drop(columns=['GeoFIPS'])

#removing the state identifier
df_countygdp['GeoName'] = df_countygdp['GeoName'].str[:-4].str.strip()

#renaming geoname to county
df_countygdp = df_countygdp.rename(columns={'GeoName': 'county'})
df_countygdp

          county  2022  2023  2024
0        Autauga   8.4   1.3  -7.8
1        Baldwin   6.1   7.6   2.8
2        Barbour  -1.2  -2.4   2.4
3           Bibb  -0.4   2.8   0.9
4         Blount   0.8   4.3   8.2
...          ...   ...   ...   ...
3122  Sweetwater  -4.1   4.0  -7.8
3123       Teton  -1.8   4.3   2.8
3124       Uinta   4.3   0.7   1.4
3125    Washakie  -1.2   2.5  -1.3
3126      Weston   0.3   3.4   9.9

[3127 rows x 4 columns]

### Dataset #3

Instructions: 
1. Change the header from Dataset #1 to something more descriptive of the dataset
2. Write a few paragraphs about this dataset. Make sure to cover
   1. Describe the important metrics, what units they are in, and giv some sense of what they mean.  For example "Fasting blood glucose in units of mg glucose per deciliter of blood.  Normal values for healthy individuals range from 70 to 100 mg/dL.  Values 100-125 are prediabetic and values >125mg/dL indicate diabetes. Values <70 indicate hypoglycemia. Fasting idicates the patient hasn't eaten in the last 8 hours.  If blood glucose is >250 or <50 at any time (regardless of the time of last meal) the patient's life may be in immediate danger"
   2. If there are any major concerns with the dataset, describe them. For example "Dataset is composed of people who are serious enough about eating healthy that they voluntarily downloaded an app dedicated to tracking their eating patterns. This sample is likely biased because of that self-selection. These people own smartphones and may be healthier and may have more disposable income than the average person.  Those who voluntarily log conscientiously and for long amounts of time are also likely even more interested in health than those who download the app and only log a bit before getting tired of it"
3. Use the cell below to 
    1. load the dataset 
    2. make the dataset tidy or demonstrate that it was already tidy
    3. demonstrate the size of the dataset
    4. find out how much data is missing, where its missing, and if its missing at random or seems to have any systematic relationships in its missingness
    5. find and flag any outliers or suspicious entries
    6. clean the data or demonstrate that it was already clean.  You may choose how to deal with missingness (dropna of fillna... how='any' or 'all') and you should justify your choice in some way
    7. You will load raw data from `data/00-raw/`, you will (optionally) write intermediate stages of your work to `data/01-interim` and you will write the final fully wrangled version of your data to `data/02-processed`
4. Optionally you can also show some summary statistics for variables that you think are important to the project
5. Feel free to add more cells here if that's helpful for you

In [5]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE

### Dataset #4

Instructions: 
1. Change the header from Dataset #1 to something more descriptive of the dataset
2. Write a few paragraphs about this dataset. Make sure to cover
   1. Describe the important metrics, what units they are in, and giv some sense of what they mean.  For example "Fasting blood glucose in units of mg glucose per deciliter of blood.  Normal values for healthy individuals range from 70 to 100 mg/dL.  Values 100-125 are prediabetic and values >125mg/dL indicate diabetes. Values <70 indicate hypoglycemia. Fasting idicates the patient hasn't eaten in the last 8 hours.  If blood glucose is >250 or <50 at any time (regardless of the time of last meal) the patient's life may be in immediate danger"
   2. If there are any major concerns with the dataset, describe them. For example "Dataset is composed of people who are serious enough about eating healthy that they voluntarily downloaded an app dedicated to tracking their eating patterns. This sample is likely biased because of that self-selection. These people own smartphones and may be healthier and may have more disposable income than the average person.  Those who voluntarily log conscientiously and for long amounts of time are also likely even more interested in health than those who download the app and only log a bit before getting tired of it"
3. Use the cell below to 
    1. load the dataset 
    2. make the dataset tidy or demonstrate that it was already tidy
    3. demonstrate the size of the dataset
    4. find out how much data is missing, where its missing, and if its missing at random or seems to have any systematic relationships in its missingness
    5. find and flag any outliers or suspicious entries
    6. clean the data or demonstrate that it was already clean.  You may choose how to deal with missingness (dropna of fillna... how='any' or 'all') and you should justify your choice in some way
    7. You will load raw data from `data/00-raw/`, you will (optionally) write intermediate stages of your work to `data/01-interim` and you will write the final fully wrangled version of your data to `data/02-processed`
4. Optionally you can also show some summary statistics for variables that you think are important to the project
5. Feel free to add more cells here if that's helpful for you

In [6]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE

### Dataset #5

Instructions: 
1. Change the header from Dataset #1 to something more descriptive of the dataset
2. Write a few paragraphs about this dataset. Make sure to cover
   1. Describe the important metrics, what units they are in, and giv some sense of what they mean.  For example "Fasting blood glucose in units of mg glucose per deciliter of blood.  Normal values for healthy individuals range from 70 to 100 mg/dL.  Values 100-125 are prediabetic and values >125mg/dL indicate diabetes. Values <70 indicate hypoglycemia. Fasting idicates the patient hasn't eaten in the last 8 hours.  If blood glucose is >250 or <50 at any time (regardless of the time of last meal) the patient's life may be in immediate danger"
   2. If there are any major concerns with the dataset, describe them. For example "Dataset is composed of people who are serious enough about eating healthy that they voluntarily downloaded an app dedicated to tracking their eating patterns. This sample is likely biased because of that self-selection. These people own smartphones and may be healthier and may have more disposable income than the average person.  Those who voluntarily log conscientiously and for long amounts of time are also likely even more interested in health than those who download the app and only log a bit before getting tired of it"
3. Use the cell below to 
    1. load the dataset 
    2. make the dataset tidy or demonstrate that it was already tidy
    3. demonstrate the size of the dataset
    4. find out how much data is missing, where its missing, and if its missing at random or seems to have any systematic relationships in its missingness
    5. find and flag any outliers or suspicious entries
    6. clean the data or demonstrate that it was already clean.  You may choose how to deal with missingness (dropna of fillna... how='any' or 'all') and you should justify your choice in some way
    7. You will load raw data from `data/00-raw/`, you will (optionally) write intermediate stages of your work to `data/01-interim` and you will write the final fully wrangled version of your data to `data/02-processed`
4. Optionally you can also show some summary statistics for variables that you think are important to the project
5. Feel free to add more cells here if that's helpful for you

In [7]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE

## Ethics

### A. Data Collection
 - [] **A.1 Informed consent**: If there are human subjects, have they given informed consent, where subjects affirmatively opt-in and have a clear understanding of the data uses to which they consent?
 - [X] **A.2 Collection bias**: Have we considered sources of bias that could be introduced during data collection and survey design and taken steps to mitigate those?

In analyzing factors such as CO₂ emissions and electricity use, we recognize that environmental conditions in certain areas may be influenced by geographic location, climate, or existing infrastructure rather than being solely attributable to data center resource usage. To address this potential collection bias, we remain mindful of external and contextual factors that could skew interpretations of the data and acknowledge these limitations when drawing conclusions.

 - [X] **A.3 Limit PII exposure**: Have we considered ways to minimize exposure of personally identifiable information (PII) for example through anonymization or not collecting information that isn't relevant for analysis?

 - [X] **A.2 Collection bias**: Have we considered sources of bias that could be introduced during data collection and survey design and taken steps to mitigate those?
       Though we are analyzing factors such as CO₂ emissions and electricity use, the environmental impacts in a certain area could be in worse conditions due to location rather than being simply a result of data center resource usage.
       
 - [X] **A.3 Limit PII exposure**: Have we considered ways to minimize exposure of personally identifiable information (PII) for example through anonymization or not collecting information that isn't relevant for analysis?
       By potentially generalizing information to county-specific and not including individual’s data, the exposure of PII would be minimized.

 - [X] **A.4 Downstream bias mitigation**: Have we considered ways to enable testing downstream results for biased outcomes (e.g., collecting data on protected group status like race or gender)?

### B. Data Storage
 - [X] **B.1 Data security**: Do we have a plan to protect and secure data (e.g., encryption at rest and in transit, access controls on internal users and third parties, access logs, and up-to-date software)?
       All the information that we plan to use from datasets would be from publicly available databases, so no confidential and secure data could be potentially compromised.
       
 - [X] **B.2 Right to be forgotten**: Do we have a mechanism through which an individual can request their personal information be removed?
 - [X] **B.3 Data retention plan**: Is there a schedule or plan to delete the data after it is no longer needed?

### C. Analysis
 - [X] **C.1 Missing perspectives**: Have we sought to address blindspots in the analysis through engagement with relevant stakeholders (e.g., checking assumptions and discussing implications with affected communities and subject matter experts)?
       A stakeholder’s perspective that may need to be considered are those of the team behind the data centers (who are subject matter experts), explaining the outcomes and necessary parts that go into powering data centers. This missing perspective may provide crucial insight and context into whatever we analyze from the data to answer our research question.

 - [X] **C.2 Dataset bias**: Have we examined the data for possible sources of bias and taken steps to mitigate or address these biases (e.g., stereotype perpetuation, confirmation bias, imbalanced classes, or omitted confounding variables)?
    Same as mentioned previously, analyzing factors such as CO₂ emissions and electricity use, their specific environmental impacts in a certain area could be resulting in more concerning data due to location rather than being simply a result of data center resource usage (which could be omitted confounding variables).
       
 - [X] **C.3 Honest representation**: Are our visualizations, summary statistics, and reports designed to honestly represent the underlying data?
 - [X] **C.4 Privacy in analysis**: Have we ensured that data with PII are not used or displayed unless necessary for the analysis?
 - [X] **C.5 Auditability**: Is the process of generating the analysis well documented and reproducible if we discover issues in the future?

### D. Modeling
 - [X] **D.1 Proxy discrimination**: Have we ensured that the model does not rely on variables or proxies for variables that are unfairly discriminatory?
 - [X] **D.2 Fairness across groups**: Have we tested model results for fairness with respect to different affected groups (e.g., tested for disparate error rates)?
 - [X] **D.3 Metric selection**: Have we considered the effects of optimizing for our defined metrics and considered additional metrics?
 - [X] **D.4 Explainability**: Can we explain in understandable terms a decision the model made in cases where a justification is needed?
 - [X] **D.5 Communicate limitations**: Have we communicated the shortcomings, limitations, and biases of the model to relevant stakeholders in ways that can be generally understood?

    This project doesn't require us to be building or deploying a predictive model, just addressing ethical concerns related to how our data analysis/results can be potentially interpreted. Environmental and economic conditions differ immensely from county to county, so certain patterns within the data could be mistaken as simple cause-and-effect relationships when they are actually just correlations. There is also a risk these countries which are hosting AI data centers could be judged unfairly if differences in their specific infrastructure, climate, or local government policies are not taken into account.

### E. Deployment
 - [X] **E.1 Monitoring and evaluation**: Do we have a clear plan to monitor the model and its impacts after it is deployed (e.g., performance monitoring, regular audit of sample predictions, human review of high-stakes decisions, reviewing downstream impacts of errors or low-confidence decisions, testing for concept drift)?
 - [X] **E.2 Redress**: Have we discussed with our organization a plan for response if users are harmed by the results (e.g., how does the data science team evaluate these cases and update analysis and models to prevent future harm)?
 - [X] **E.3 Roll back**: Is there a way to turn off or roll back the model in production if necessary?
 - [X] **E.4 Unintended use**: Have we taken steps to identify and prevent unintended uses and abuse of the model and do we have a plan to monitor these once the model is deployed?
   
    To address these concerns previously listed, our team will be very diligent in explaining our limitations of the analysis and avoiding making causal claims without a strong reason to do so. We will present our results with appropriate context and acknowledge uncertainty in the data. By framing our conclusions carefully and avoiding generalizations, we aim to reduce the risk of our findings being misinterpreted.

## Team Expectations

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Project Timeline Proposal

| Meeting Date  | Meeting Time| Completed Before Meeting  | Discuss at Meeting |
|---|---|---|---|
| 2/11  | 5 PM  | Find at least one new potential dataset  |  Choose best datasets and assign sections of data checkpoint. Start wrangling data   |
| 2/18  | Before 11:59 PM  | NA | Submit data checkpoint   |
| 2/25  | 5 PM  | Review data checkpoint feedback. | EDA discussion, assign sections of EDA checkpoint |
| 3/04  | Before 11:59 PM  |  NA | Submit EDA checkpoint |
| 3/11  | 5 PM  | Final project report. At least one note about potential modification | If anything needs to be modified. Finalize and submit project. Discuss video logistics |
| 3/15  | 5 PM  |  Video logistics | Film video |
| 3/18  | Before 11:59 PM  |  NA | Submit video and final project and team evaluation survey |