## Rubric

Instructions: DELETE this cell before you submit via a `git push` to your repo before deadline. This cell is for your reference only and is not needed in your report. 

 Scoring: Out of 10 points

- Each Developing  => -2 pts
- Each Unsatisfactory/Missing => -4 pts
  - until the score is 0

If students address the detailed feedback in a future checkpoint they will earn these points back






|                                  | **Unsatisfactory**                                                                                                                                                                                                                                                                                                                        | **Developing**                                                                                                                                                                                                       | **Proficient**                                                                                                                                                                                            | **Excellent**                                                                                                                                                                            |
|----------------------------------|---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
| **EDA relevance**                | EDA is mostly neither relevant to the question nor helpful in figuring out how to address the question. Or the EDA does address the question, but many obviously relevant variables / analyses / figures were not included. | EDA is partly irrelevant/unhelpful. EDA missed one or two obvioulsy relevant analysis (distributions of single variables or relationships between variables) | EDA includes the obviously relevant / helpful variables in addressing the question.                                                              | Thorough EDA fully explored the dataset                                                                                                                 |
| **EDA analysis and description** | Many of the analyses are poor choices (e.g., using means instead of medians for obviously skewed data), or are poorly described in the text, or do not aid understanding the data                                                                                                                                                     | Some of the analyses are poor choices, or are poorly described in the text, or do not aid understanding the data                                                                                                 | All analyses are correct choices. Only one or two have minor issues in the text descriptions supporting them. Mostly they fit well with other elements of the EDA and support understanding the data  | All analyses are correct choices with clear text descriptions supporting them. The figures fit well with the other elements of the EDA, producing a clear understanding of the data. |
| **EDA figures**                  | Many of the figures are poor plot choices (e.g., using a bar plot to represent a time series where it would be better to use a line plot) or have poor aesthetics (including colormap, data point shape/color, axis labels, titles, annotations, text legibility) or do not aid understanding the data                                | Some of the figures are poor plot choices or have poor aesthetics. Some figures do not aid understanding the data                                                                                                | All figures are correct plot choices. Only one or two have minor questionable aesthetic choices. The figures mostly fit well with the other elements of the EDA and support understanding the data    | All figures are correct plot choices with beautiful aesthetics. The figures fit well with the other elements of the EDA, producing a clear understanding of the data.                |

# COGS 108 - EDA Checkpoint

## Authors

Instructions: REPLACE the contents of this cell with your team list and their contributions. Note that this will change over the course of the checkpoints

This is a modified [CRediT taxonomy of contributions](https://credit.niso.org). For each group member please list how they contributed to this project using these terms:
> Analysis, Background research, Conceptualization, Data curation, Experimental investigation, Methodology, Project administration, Software, Visualization, Writing – original draft, Writing – review & editing

Example team list and credits:
- Alice Anderson: Conceptualization, Data curation, Methodology, Writing - original draft
- Bob Barker:  Analysis, Software, Visualization
- Charlie Chang: Project administration, Software, Writing - review & editing
- Dani Delgado: Analysis, Background research, Visualization, Writing - original draft

# Research Question

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Background and Prior Work

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

# Hypothesis

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Data

### Data overview

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your data checkpoint feedback

In [1]:
# Run this code every time when you're actively developing modules in .py files.  It's not needed if you aren't making modules
#
## this code is necessary for making sure that any modules we load are updated here 
## when their source code .py files are modified

%load_ext autoreload
%autoreload 2

In [2]:
# Setup code -- Run only once after cloning!!! 
#
# this code downloads the data from its source to the `data/00-raw/` directory
# if the data hasn't updated you don't need to do this again!

# if you don't already have these packages (you should!) uncomment this line
# %pip install requests tqdm

import sys
sys.path.append('./modules') # this tells python where to look for modules to import

import get_data # this is where we get the function we need to download data

# replace the urls and filenames in this list with your actual datafiles
# yes you can use Google drive share links or whatever
# format is a list of dictionaries; 
# each dict has keys of 
#   'url' where the resource is located
#   'filename' for the local filename where it will be stored 
datafiles = [
    { 'url': 'https://raw.githubusercontent.com/fivethirtyeight/data/refs/heads/master/airline-safety/airline-safety.csv', 'filename':'airline-safety.csv'},
    { 'url': 'https://raw.githubusercontent.com/fivethirtyeight/data/refs/heads/master/bad-drivers/bad-drivers.csv', 'filename':'bad-drivers.csv'}
]

get_data.get_raw(datafiles,destination_directory='data/00-raw/')

Overall Download Progress:   0%|          | 0/2 [00:00<?, ?it/s]
Downloading airline-safety.csv:   0%|          | 0.00/1.23k [00:00<?, ?B/s]
Overall Download Progress:  50%|█████     | 1/2 [00:00<00:00,  6.38it/s]

Successfully downloaded: airline-safety.csv

Downloading bad-drivers.csv:   0%|          | 0.00/1.37k [00:00<?, ?B/s]
Overall Download Progress: 100%|██████████| 2/2 [00:00<00:00,  6.21it/s]

Successfully downloaded: bad-drivers.csv

### Dataset #1 

Instructions: REPLACE the contents of this cell and the one below with your work, including any updates to recover points lost in your data checkpoint feedback

In [3]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

### Dataset #2
 as above, add any more copies of this that you need to given how many datasets you have

In [4]:
## YOUR CODE TO LOAD/CLEAN/TIDY/WRANGLE THE DATA GOES HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

## Results

### Exploratory Data Analysis

Instructions: replace the words in this subsection with whatever words you need to setup and preview the EDA you're going to do.   

Please explicitly load the fully wrangled data you will use from `data/02-processed`.  This is a good idea rather than forcing people to re-run the data getting / wrangling cells above.  Sometimes it takes a long time to get / wrangle data compared to reloading the fixed up dataset.

Carry out whatever EDA you need to for your project in the code cells below.  Because every project will be different we can't really give you much of a template at this point. But please make sure you describe the what and why in text here as well as providing interpretation of results and context.

Please note that you should consider the use of python modules in your work.  Any code which gets called repeatedly should be modularized. So if you run the same pre-processing, analysis or visualiazation on different subsets of the data, then you should turn that into a function or class.  Put that function or class in a .py file that lives in `modules/`.  Import the module you made and use it to get your work done.  For reference see `get_raw()` which is inside `modules/get_data.py`.

#### Our datasets

Some more words and stuff.  Remember notebooks work best if you interleave the code that generates a result with properly annotate figures and text that puts these results into context.

In [30]:
# loading clean datasets
import pandas as pd
df_dc = pd.read_csv("data/02-processed/df_datacenters_clean.csv")
df_countygdp = pd.read_csv("data/02-processed/df_countygdp_clean.csv")
df_emissions = pd.read_csv("data/02-processed/df_emissions_clean.csv")
df_water = pd.read_csv("data/02-processed/df_water_clean.csv")
df_electricity = pd.read_csv("data/02-processed/df_electricity_clean.csv")

In [42]:
# df emissions
df_co2 = df_emissions[(df_emissions['sector-name']=='Industrial carbon dioxide emissions') & (df_emissions['year']==2021) & (df_co2['fuel-name'] == 'All Fuels')]
df_co2 = df_co2.rename(columns={
    'state-name': 'state',
})

# new df counties: containing all counties 
df_counties = df_countygdp[['county']].copy()

#saving df counties to data/02processed
df_counties.to_csv('data/02-processed/df_counties.csv',index=False)

#aggregating total sqft per county in df_dc
total_sqft = df_dc.groupby(['state','county'])['sqft'].sum().reset_index()
total_sqft.rename(columns={'sqft':'total_sqft'}, inplace=True)

# getting columns in df electricity for 2021
elec_2021_cols = [col for col in df_electricity.columns if "2021" in col]
df_electricity['elec_price_2021'] = df_electricity[elec_2021_cols].mean(axis=1)
df_electricity = df_electricity[['state', 'elec_price_2021']].copy()

In [43]:
df_dc.head()

         id           state      county        sqft
0   2744301      new jersey   middlesex    105786.0
1   9474864  north carolina    caldwell   3407194.0
2  13924557            iowa        polk  11169421.0
3  14593270  north carolina     catawba   5431080.0
4  14930068      new mexico  bernalillo    158463.0

In [44]:
df_co2.head()

,year,state,sector-name,fuel-name,value
58838,2021,Alabama,Industrial carbon dioxide emissions,All Fuels,19.640576
58860,2021,Alaska,Industrial carbon dioxide emissions,All Fuels,18.390715
58868,2021,Arizona,Industrial carbon dioxide emissions,All Fuels,4.625649
58902,2021,Arkansas,Industrial carbon dioxide emissions,All Fuels,8.281442
58912,2021,California,Industrial carbon dioxide emissions,All Fuels,63.945572

In [45]:
df_countygdp.head()

   GeoFIPS   county  gdp2022  gdp2023  gdp2024    state
0     1001  autauga      8.4      1.3     -7.8  alabama
1     1003  baldwin      6.1      7.6      2.8  alabama
2     1005  barbour     -1.2     -2.4      2.4  alabama
3     1007     bibb     -0.4      2.8      0.9  alabama
4     1009   blount      0.8      4.3      8.2  alabama

In [46]:
df_water.head()

,state,STATEFIPS,county,COUNTYFIPS,FIPS,YEAR,TP-TotPop,PS-GWPop,PS-SWPop,PS-TOPop,...,TO-WGWTo,TO-WSWFr,TO-WSWSa,TO-WSWTo,TO-WFrTo,TO-WSaTo,TO-Wtotl,TO-CUsFrPartial,TO-CUsSaPartial,TO-CUTotPartial
0,alabama,1,autauga,1,1001,2015,55.347,--,--,48.998,...,10.69,45.72,0.0,45.72,56.41,0.0,56.41,13.18,0.0,13.18
1,alabama,1,baldwin,3,1003,2015,203.709,--,--,174.907,...,73.38,11.32,0.0,11.32,84.70,0.0,84.70,58.28,0.0,58.28
2,alabama,1,barbour,5,1005,2015,26.489,--,--,24.587,...,6.06,2.96,0.0,2.96,9.02,0.0,9.02,2.96,0.0,2.96
3,alabama,1,bibb,7,1007,2015,22.583,--,--,20.947,...,5.67,0.20,0.0,0.20,5.87,0.0,5.87,0.19,0.0,0.19
4,alabama,1,blount,9,1009,2015,57.673,--,--,44.815,...,4.64,55.43,0.0,55.43,60.07,0.0,60.07,1.08,0.0,1.08

In [47]:
df_electricity.head()

           state  elec_price_2021
0    connecticut        16.527500
1          maine        12.906667
2  massachusetts        16.954167
3  new hampshire        16.142500
4   rhode island        15.532500

In [48]:
# cleaning names of counties and states functions

def clean_county(county):
    county = str(county).strip().lower()

    for suffix in [" county", 
               " parish", 
               " borough", 
               " census area", 
               " municipality", 
               "city and borough"]:
        if county.endswith(suffix):
            county = county[:-len(suffix)]
    return county

def clean_state(state):
    state = str(state).strip().lower()
    return state

for df in [df_dc, df_countygdp, total_sqft, df_water]:
    df['county'] = df['county'].apply(clean_county)
    df['state'] = df['state'].apply(clean_state)

df_co2['state'] = df_co2['state'].apply(clean_state)
df_electricity['state'] = df_electricity['state'].apply(clean_state)

#### Merging datasets

In [50]:
# merging county gdp with total sqft from df_dc
df = df_countygdp.merge(total_sqft, on=['state','county'],how='left')

#filling nan sqft with 0
df['total_sqft'] = df['total_sqft'].fillna(0)

#merging df w df_water
df = df.merge(df_water, on=['state','county'], how='left')

#merging df w df_co2
df = df.merge(df_co2, on=['state'], how='left')

#merging df w df_electricity

df = df.merge(df_electricity, on=['state'], how='left')

#dropping irrelevant columns 

df

,GeoFIPS,county,gdp2022,gdp2023,gdp2024,state,total_sqft,STATEFIPS,COUNTYFIPS,FIPS,...,TO-WSaTo,TO-Wtotl,TO-CUsFrPartial,TO-CUsSaPartial,TO-CUTotPartial,year,sector-name,fuel-name,value,elec_price_2021
0,1001,autauga,8.4,1.3,-7.8,alabama,0.0,1.0,1.0,1001.0,...,0.00,56.41,13.18,0.0,13.18,2021,Industrial carbon dioxide emissions,All Fuels,19.640576,11.823333
1,1003,baldwin,6.1,7.6,2.8,alabama,0.0,1.0,3.0,1003.0,...,0.00,84.70,58.28,0.0,58.28,2021,Industrial carbon dioxide emissions,All Fuels,19.640576,11.823333
2,1005,barbour,-1.2,-2.4,2.4,alabama,0.0,1.0,5.0,1005.0,...,0.00,9.02,2.96,0.0,2.96,2021,Industrial carbon dioxide emissions,All Fuels,19.640576,11.823333
3,1007,bibb,-0.4,2.8,0.9,alabama,0.0,1.0,7.0,1007.0,...,0.00,5.87,0.19,0.0,0.19,2021,Industrial carbon dioxide emissions,All Fuels,19.640576,11.823333
4,1009,blount,0.8,4.3,8.2,alabama,0.0,1.0,9.0,1009.0,...,0.00,60.07,1.08,0.0,1.08,2021,Industrial carbon dioxide emissions,All Fuels,19.640576,11.823333
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
3059,56037,sweetwater,-4.1,4.0,-7.8,wyoming,0.0,56.0,37.0,56037.0,...,5.77,151.96,48.19,0.0,48.19,2021,Industrial carbon dioxide emissions,All Fuels,11.162642,9.686667
3060,56039,teton,-1.8,4.3,2.8,wyoming,0.0,56.0,39.0,56039.0,...,0.00,111.52,22.57,0.0,22.57,2021,Industrial carbon dioxide emissions,All Fuels,11.162642,9.686667
3061,56041,uinta,4.3,0.7,1.4,wyoming,0.0,56.0,41.0,56041.0,...,0.05,387.90,111.64,0.0,111.64,2021,Industrial carbon dioxide emissions,All Fuels,11.162642,9.686667
3062,56043,washakie,-1.2,2.5,-1.3,wyoming,0.0,56.0,43.0,56043.0,...,0.35,268.65,64.22,0.0,64.22,2021,Industrial carbon dioxide emissions,All Fuels,11.162642,9.686667
3063,56045,weston,0.3,3.4,9.9,wyoming,0.0,56.0,45.0,56045.0,...,0.66,25.36,5.01,0.0,5.01,2021,Industrial carbon dioxide emissions,All Fuels,11.162642,9.686667

#### Creating treatment variables

In [15]:

# has_dc: 1 if county has a data center, 0 otherwise
df['has_dc'] = df['total_sqft'].apply(lambda x: 1 if x > 0 else 0)

# large_dc if sqft over 1,000,000, 1 if yes, 0 otherwise
df['large_dc'] = df['total_sqft'].apply(lambda x: 1 if x > 1_000_000 else 0)

In [16]:
print(df['has_dc'].value_counts())
print(df['large_dc'].value_counts())

has_dc
0    2847
1     217
Name: count, dtype: int64
large_dc
0    2992
1      72
Name: count, dtype: int64

#### Section 1 of EDA - please give it a better title than this

Some more words and stuff.  Remember notebooks work best if you interleave the code that generates a result with properly annotate figures and text that puts these results into context.

In [17]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

#### Section 2 of EDA if you need it  - please give it a better title than this

Some more words and stuff.  Remember notebooks work best if you interleave the code that generates a result with properly annotate figures and text that puts these results into context.

In [18]:
## YOUR CODE HERE
## FEEL FREE TO ADD MULTIPLE CELLS PER SECTION

## Ethics

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Team Expectations

Instructions: REPLACE the contents of this cell with your work, including any updates to recover points lost in your proposal feedback

## Project Timeline Proposal

Instructions: Replace this with your timeline.  **PLEASE UPDATE your Timeline!** No battle plan survives contact with the enemy, so make sure we understand how your plans have changed.  Also if you have lost points on the previous checkpoint fix them